require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DeptToursController do

  # This should return the minimal set of attributes required to create a valid
  # DeptTour. As you add validations to DeptTour, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DeptToursController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dept_tours as @dept_tours" do
      dept_tour = DeptTour.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dept_tours).should eq([dept_tour])
    end
  end

  describe "GET show" do
    it "assigns the requested dept_tour as @dept_tour" do
      dept_tour = DeptTour.create! valid_attributes
      get :show, {:id => dept_tour.to_param}, valid_session
      assigns(:dept_tour).should eq(dept_tour)
    end
  end

  describe "GET new" do
    it "assigns a new dept_tour as @dept_tour" do
      get :new, {}, valid_session
      assigns(:dept_tour).should be_a_new(DeptTour)
    end
  end

  describe "GET edit" do
    it "assigns the requested dept_tour as @dept_tour" do
      dept_tour = DeptTour.create! valid_attributes
      get :edit, {:id => dept_tour.to_param}, valid_session
      assigns(:dept_tour).should eq(dept_tour)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DeptTour" do
        expect {
          post :create, {:dept_tour => valid_attributes}, valid_session
        }.to change(DeptTour, :count).by(1)
      end

      it "assigns a newly created dept_tour as @dept_tour" do
        post :create, {:dept_tour => valid_attributes}, valid_session
        assigns(:dept_tour).should be_a(DeptTour)
        assigns(:dept_tour).should be_persisted
      end

      it "redirects to the created dept_tour" do
        post :create, {:dept_tour => valid_attributes}, valid_session
        response.should redirect_to(DeptTour.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dept_tour as @dept_tour" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeptTour.any_instance.stub(:save).and_return(false)
        post :create, {:dept_tour => { "name" => "invalid value" }}, valid_session
        assigns(:dept_tour).should be_a_new(DeptTour)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeptTour.any_instance.stub(:save).and_return(false)
        post :create, {:dept_tour => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dept_tour" do
        dept_tour = DeptTour.create! valid_attributes
        # Assuming there are no other dept_tours in the database, this
        # specifies that the DeptTour created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DeptTour.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => dept_tour.to_param, :dept_tour => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested dept_tour as @dept_tour" do
        dept_tour = DeptTour.create! valid_attributes
        put :update, {:id => dept_tour.to_param, :dept_tour => valid_attributes}, valid_session
        assigns(:dept_tour).should eq(dept_tour)
      end

      it "redirects to the dept_tour" do
        dept_tour = DeptTour.create! valid_attributes
        put :update, {:id => dept_tour.to_param, :dept_tour => valid_attributes}, valid_session
        response.should redirect_to(dept_tour)
      end
    end

    describe "with invalid params" do
      it "assigns the dept_tour as @dept_tour" do
        dept_tour = DeptTour.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeptTour.any_instance.stub(:save).and_return(false)
        put :update, {:id => dept_tour.to_param, :dept_tour => { "name" => "invalid value" }}, valid_session
        assigns(:dept_tour).should eq(dept_tour)
      end

      it "re-renders the 'edit' template" do
        dept_tour = DeptTour.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeptTour.any_instance.stub(:save).and_return(false)
        put :update, {:id => dept_tour.to_param, :dept_tour => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dept_tour" do
      dept_tour = DeptTour.create! valid_attributes
      expect {
        delete :destroy, {:id => dept_tour.to_param}, valid_session
      }.to change(DeptTour, :count).by(-1)
    end

    it "redirects to the dept_tours list" do
      dept_tour = DeptTour.create! valid_attributes
      delete :destroy, {:id => dept_tour.to_param}, valid_session
      response.should redirect_to(dept_tours_url)
    end
  end

end
