require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ResumeBooksController do

  # This should return the minimal set of attributes required to create a valid
  # ResumeBook. As you add validations to ResumeBook, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ResumeBooksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all resume_books as @resume_books" do
      resume_book = ResumeBook.create! valid_attributes
      get :index, {}, valid_session
      assigns(:resume_books).should eq([resume_book])
    end
  end

  describe "GET show" do
    it "assigns the requested resume_book as @resume_book" do
      resume_book = ResumeBook.create! valid_attributes
      get :show, {:id => resume_book.to_param}, valid_session
      assigns(:resume_book).should eq(resume_book)
    end
  end

  describe "GET new" do
    it "assigns a new resume_book as @resume_book" do
      get :new, {}, valid_session
      assigns(:resume_book).should be_a_new(ResumeBook)
    end
  end

  describe "GET edit" do
    it "assigns the requested resume_book as @resume_book" do
      resume_book = ResumeBook.create! valid_attributes
      get :edit, {:id => resume_book.to_param}, valid_session
      assigns(:resume_book).should eq(resume_book)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ResumeBook" do
        expect {
          post :create, {:resume_book => valid_attributes}, valid_session
        }.to change(ResumeBook, :count).by(1)
      end

      it "assigns a newly created resume_book as @resume_book" do
        post :create, {:resume_book => valid_attributes}, valid_session
        assigns(:resume_book).should be_a(ResumeBook)
        assigns(:resume_book).should be_persisted
      end

      it "redirects to the created resume_book" do
        post :create, {:resume_book => valid_attributes}, valid_session
        response.should redirect_to(ResumeBook.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved resume_book as @resume_book" do
        # Trigger the behavior that occurs when invalid params are submitted
        ResumeBook.any_instance.stub(:save).and_return(false)
        post :create, {:resume_book => { "title" => "invalid value" }}, valid_session
        assigns(:resume_book).should be_a_new(ResumeBook)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ResumeBook.any_instance.stub(:save).and_return(false)
        post :create, {:resume_book => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested resume_book" do
        resume_book = ResumeBook.create! valid_attributes
        # Assuming there are no other resume_books in the database, this
        # specifies that the ResumeBook created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ResumeBook.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => resume_book.to_param, :resume_book => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested resume_book as @resume_book" do
        resume_book = ResumeBook.create! valid_attributes
        put :update, {:id => resume_book.to_param, :resume_book => valid_attributes}, valid_session
        assigns(:resume_book).should eq(resume_book)
      end

      it "redirects to the resume_book" do
        resume_book = ResumeBook.create! valid_attributes
        put :update, {:id => resume_book.to_param, :resume_book => valid_attributes}, valid_session
        response.should redirect_to(resume_book)
      end
    end

    describe "with invalid params" do
      it "assigns the resume_book as @resume_book" do
        resume_book = ResumeBook.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ResumeBook.any_instance.stub(:save).and_return(false)
        put :update, {:id => resume_book.to_param, :resume_book => { "title" => "invalid value" }}, valid_session
        assigns(:resume_book).should eq(resume_book)
      end

      it "re-renders the 'edit' template" do
        resume_book = ResumeBook.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ResumeBook.any_instance.stub(:save).and_return(false)
        put :update, {:id => resume_book.to_param, :resume_book => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested resume_book" do
      resume_book = ResumeBook.create! valid_attributes
      expect {
        delete :destroy, {:id => resume_book.to_param}, valid_session
      }.to change(ResumeBook, :count).by(-1)
    end

    it "redirects to the resume_books list" do
      resume_book = ResumeBook.create! valid_attributes
      delete :destroy, {:id => resume_book.to_param}, valid_session
      response.should redirect_to(resume_books_url)
    end
  end

end
